// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/hayeah/hubsync"
)

// Injectors from wire.go:

func InitializeHubApp(cfg *hubsync.HubConfig) (*hubsync.HubApp, func(), error) {
	hubStore, cleanup, err := hubsync.ProvideHubStore(cfg)
	if err != nil {
		return nil, nil, err
	}
	scanner, err := hubsync.ProvideScanner(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	watcher, cleanup2, err := hubsync.ProvideWatcher(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	broadcaster := hubsync.NewBroadcaster()
	hub := hubsync.NewHub(hubStore, scanner, watcher, broadcaster)
	server := hubsync.ProvideServer(hub, cfg)
	hubApp := &hubsync.HubApp{
		Server: server,
		Hub:    hub,
	}
	return hubApp, func() {
		cleanup2()
		cleanup()
	}, nil
}

func InitializeClientApp(cfg *hubsync.ClientConfig) (*hubsync.ClientApp, func(), error) {
	clientStore, cleanup, err := hubsync.ProvideClientStore(cfg)
	if err != nil {
		return nil, nil, err
	}
	client := hubsync.ProvideClient(clientStore, cfg)
	clientApp := &hubsync.ClientApp{
		Client: client,
	}
	return clientApp, func() {
		cleanup()
	}, nil
}
