// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/hayeah/hubsync"
)

// Injectors from wire.go:

func InitializeHubApp(cfg *hubsync.HubConfig) (*hubsync.HubApp, func(), error) {
	hasher, err := hubsync.ProvideHubHasher(cfg)
	if err != nil {
		return nil, nil, err
	}
	hubStoreConfig := hubsync.ProvideHubStoreConfig(cfg, hasher)
	hubStore, cleanup, err := hubsync.NewHubStore(hubStoreConfig)
	if err != nil {
		return nil, nil, err
	}
	scannerConfig, err := hubsync.ProvideScannerConfig(cfg, hasher)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	scanner := hubsync.NewScanner(scannerConfig)
	watcherConfig := hubsync.ProvideWatcherConfig(cfg)
	watcher, cleanup2, err := hubsync.NewWatcher(watcherConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	broadcaster := hubsync.NewBroadcaster()
	hub := hubsync.NewHub(hubStore, scanner, watcher, broadcaster, hasher)
	serverConfig := hubsync.ProvideServerConfig(cfg, hasher)
	server := hubsync.NewServer(hub, serverConfig)
	hubApp := &hubsync.HubApp{
		Server: server,
		Hub:    hub,
	}
	return hubApp, func() {
		cleanup2()
		cleanup()
	}, nil
}

func InitializeClientApp(cfg *hubsync.ClientConfig) (*hubsync.ClientApp, func(), error) {
	clientStoreConfig := hubsync.ProvideClientStoreConfig(cfg)
	clientStore, cleanup, err := hubsync.OpenClientStore(clientStoreConfig)
	if err != nil {
		return nil, nil, err
	}
	client := hubsync.ProvideClient(clientStore, cfg)
	clientApp := &hubsync.ClientApp{
		Client: client,
	}
	return clientApp, func() {
		cleanup()
	}, nil
}
