// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: hubsync.proto

package hubsync

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntryKind int32

const (
	EntryKind_FILE      EntryKind = 0
	EntryKind_DIRECTORY EntryKind = 1
	EntryKind_SYMLINK   EntryKind = 2
)

// Enum value maps for EntryKind.
var (
	EntryKind_name = map[int32]string{
		0: "FILE",
		1: "DIRECTORY",
		2: "SYMLINK",
	}
	EntryKind_value = map[string]int32{
		"FILE":      0,
		"DIRECTORY": 1,
		"SYMLINK":   2,
	}
)

func (x EntryKind) Enum() *EntryKind {
	p := new(EntryKind)
	*p = x
	return p
}

func (x EntryKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryKind) Descriptor() protoreflect.EnumDescriptor {
	return file_hubsync_proto_enumTypes[0].Descriptor()
}

func (EntryKind) Type() protoreflect.EnumType {
	return &file_hubsync_proto_enumTypes[0]
}

func (x EntryKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryKind.Descriptor instead.
func (EntryKind) EnumDescriptor() ([]byte, []int) {
	return file_hubsync_proto_rawDescGZIP(), []int{0}
}

type OpKind int32

const (
	OpKind_OP_CREATE OpKind = 0
	OpKind_OP_UPDATE OpKind = 1
	OpKind_OP_DELETE OpKind = 2
)

// Enum value maps for OpKind.
var (
	OpKind_name = map[int32]string{
		0: "OP_CREATE",
		1: "OP_UPDATE",
		2: "OP_DELETE",
	}
	OpKind_value = map[string]int32{
		"OP_CREATE": 0,
		"OP_UPDATE": 1,
		"OP_DELETE": 2,
	}
)

func (x OpKind) Enum() *OpKind {
	p := new(OpKind)
	*p = x
	return p
}

func (x OpKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpKind) Descriptor() protoreflect.EnumDescriptor {
	return file_hubsync_proto_enumTypes[1].Descriptor()
}

func (OpKind) Type() protoreflect.EnumType {
	return &file_hubsync_proto_enumTypes[1]
}

func (x OpKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpKind.Descriptor instead.
func (OpKind) EnumDescriptor() ([]byte, []int) {
	return file_hubsync_proto_rawDescGZIP(), []int{1}
}

type ConflictPolicy int32

const (
	ConflictPolicy_FAIL        ConflictPolicy = 0 // partial success, conflicts returned
	ConflictPolicy_HUB_WINS    ConflictPolicy = 1 // drop conflicting client changes silently
	ConflictPolicy_CLIENT_WINS ConflictPolicy = 2 // force overwrite hub
)

// Enum value maps for ConflictPolicy.
var (
	ConflictPolicy_name = map[int32]string{
		0: "FAIL",
		1: "HUB_WINS",
		2: "CLIENT_WINS",
	}
	ConflictPolicy_value = map[string]int32{
		"FAIL":        0,
		"HUB_WINS":    1,
		"CLIENT_WINS": 2,
	}
)

func (x ConflictPolicy) Enum() *ConflictPolicy {
	p := new(ConflictPolicy)
	*p = x
	return p
}

func (x ConflictPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConflictPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_hubsync_proto_enumTypes[2].Descriptor()
}

func (ConflictPolicy) Type() protoreflect.EnumType {
	return &file_hubsync_proto_enumTypes[2]
}

func (x ConflictPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConflictPolicy.Descriptor instead.
func (ConflictPolicy) EnumDescriptor() ([]byte, []int) {
	return file_hubsync_proto_rawDescGZIP(), []int{2}
}

type SyncEvent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Path    string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*SyncEvent_Change
	//	*SyncEvent_Delete
	Event         isSyncEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncEvent) Reset() {
	*x = SyncEvent{}
	mi := &file_hubsync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncEvent) ProtoMessage() {}

func (x *SyncEvent) ProtoReflect() protoreflect.Message {
	mi := &file_hubsync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncEvent.ProtoReflect.Descriptor instead.
func (*SyncEvent) Descriptor() ([]byte, []int) {
	return file_hubsync_proto_rawDescGZIP(), []int{0}
}

func (x *SyncEvent) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SyncEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SyncEvent) GetEvent() isSyncEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SyncEvent) GetChange() *FileChange {
	if x != nil {
		if x, ok := x.Event.(*SyncEvent_Change); ok {
			return x.Change
		}
	}
	return nil
}

func (x *SyncEvent) GetDelete() *FileDelete {
	if x != nil {
		if x, ok := x.Event.(*SyncEvent_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

type isSyncEvent_Event interface {
	isSyncEvent_Event()
}

type SyncEvent_Change struct {
	Change *FileChange `protobuf:"bytes,3,opt,name=change,proto3,oneof"`
}

type SyncEvent_Delete struct {
	Delete *FileDelete `protobuf:"bytes,4,opt,name=delete,proto3,oneof"`
}

func (*SyncEvent_Change) isSyncEvent_Event() {}

func (*SyncEvent_Delete) isSyncEvent_Event() {}

type FileChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          EntryKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=hubsync.EntryKind" json:"kind,omitempty"`
	Digest        []byte                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Mode          uint32                 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	Mtime         int64                  `protobuf:"varint,5,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"` // inline blob for files <= 64KB; empty for large files
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChange) Reset() {
	*x = FileChange{}
	mi := &file_hubsync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChange) ProtoMessage() {}

func (x *FileChange) ProtoReflect() protoreflect.Message {
	mi := &file_hubsync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChange.ProtoReflect.Descriptor instead.
func (*FileChange) Descriptor() ([]byte, []int) {
	return file_hubsync_proto_rawDescGZIP(), []int{1}
}

func (x *FileChange) GetKind() EntryKind {
	if x != nil {
		return x.Kind
	}
	return EntryKind_FILE
}

func (x *FileChange) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *FileChange) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileChange) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileChange) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *FileChange) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type FileDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDelete) Reset() {
	*x = FileDelete{}
	mi := &file_hubsync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDelete) ProtoMessage() {}

func (x *FileDelete) ProtoReflect() protoreflect.Message {
	mi := &file_hubsync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDelete.ProtoReflect.Descriptor instead.
func (*FileDelete) Descriptor() ([]byte, []int) {
	return file_hubsync_proto_rawDescGZIP(), []int{2}
}

type PushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ops           []*PushOp              `protobuf:"bytes,1,rep,name=ops,proto3" json:"ops,omitempty"`
	OnConflict    ConflictPolicy         `protobuf:"varint,2,opt,name=on_conflict,json=onConflict,proto3,enum=hubsync.ConflictPolicy" json:"on_conflict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_hubsync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hubsync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_hubsync_proto_rawDescGZIP(), []int{3}
}

func (x *PushRequest) GetOps() []*PushOp {
	if x != nil {
		return x.Ops
	}
	return nil
}

func (x *PushRequest) GetOnConflict() ConflictPolicy {
	if x != nil {
		return x.OnConflict
	}
	return ConflictPolicy_FAIL
}

type PushOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Op            OpKind                 `protobuf:"varint,2,opt,name=op,proto3,enum=hubsync.OpKind" json:"op,omitempty"`
	BaseVersion   uint64                 `protobuf:"varint,3,opt,name=base_version,json=baseVersion,proto3" json:"base_version,omitempty"` // version this edit is based on (from hub_tree.version)
	Digest        []byte                 `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`                               // SHA-256 of new content
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`                                   // blob content (inline)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushOp) Reset() {
	*x = PushOp{}
	mi := &file_hubsync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushOp) ProtoMessage() {}

func (x *PushOp) ProtoReflect() protoreflect.Message {
	mi := &file_hubsync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushOp.ProtoReflect.Descriptor instead.
func (*PushOp) Descriptor() ([]byte, []int) {
	return file_hubsync_proto_rawDescGZIP(), []int{4}
}

func (x *PushOp) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PushOp) GetOp() OpKind {
	if x != nil {
		return x.Op
	}
	return OpKind_OP_CREATE
}

func (x *PushOp) GetBaseVersion() uint64 {
	if x != nil {
		return x.BaseVersion
	}
	return 0
}

func (x *PushOp) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *PushOp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*PushResult          `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_hubsync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hubsync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_hubsync_proto_rawDescGZIP(), []int{5}
}

func (x *PushResponse) GetResults() []*PushResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type PushResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*PushResult_Accepted
	//	*PushResult_Conflict
	Outcome       isPushResult_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResult) Reset() {
	*x = PushResult{}
	mi := &file_hubsync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResult) ProtoMessage() {}

func (x *PushResult) ProtoReflect() protoreflect.Message {
	mi := &file_hubsync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResult.ProtoReflect.Descriptor instead.
func (*PushResult) Descriptor() ([]byte, []int) {
	return file_hubsync_proto_rawDescGZIP(), []int{6}
}

func (x *PushResult) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PushResult) GetOutcome() isPushResult_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *PushResult) GetAccepted() *PushAccepted {
	if x != nil {
		if x, ok := x.Outcome.(*PushResult_Accepted); ok {
			return x.Accepted
		}
	}
	return nil
}

func (x *PushResult) GetConflict() *PushConflict {
	if x != nil {
		if x, ok := x.Outcome.(*PushResult_Conflict); ok {
			return x.Conflict
		}
	}
	return nil
}

type isPushResult_Outcome interface {
	isPushResult_Outcome()
}

type PushResult_Accepted struct {
	Accepted *PushAccepted `protobuf:"bytes,2,opt,name=accepted,proto3,oneof"`
}

type PushResult_Conflict struct {
	Conflict *PushConflict `protobuf:"bytes,3,opt,name=conflict,proto3,oneof"`
}

func (*PushResult_Accepted) isPushResult_Outcome() {}

func (*PushResult_Conflict) isPushResult_Outcome() {}

type PushAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"` // new version assigned by hub
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushAccepted) Reset() {
	*x = PushAccepted{}
	mi := &file_hubsync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushAccepted) ProtoMessage() {}

func (x *PushAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_hubsync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushAccepted.ProtoReflect.Descriptor instead.
func (*PushAccepted) Descriptor() ([]byte, []int) {
	return file_hubsync_proto_rawDescGZIP(), []int{7}
}

func (x *PushAccepted) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type PushConflict struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Reason         string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	CurrentVersion uint64                 `protobuf:"varint,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	CurrentDigest  []byte                 `protobuf:"bytes,3,opt,name=current_digest,json=currentDigest,proto3" json:"current_digest,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PushConflict) Reset() {
	*x = PushConflict{}
	mi := &file_hubsync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushConflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushConflict) ProtoMessage() {}

func (x *PushConflict) ProtoReflect() protoreflect.Message {
	mi := &file_hubsync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushConflict.ProtoReflect.Descriptor instead.
func (*PushConflict) Descriptor() ([]byte, []int) {
	return file_hubsync_proto_rawDescGZIP(), []int{8}
}

func (x *PushConflict) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PushConflict) GetCurrentVersion() uint64 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

func (x *PushConflict) GetCurrentDigest() []byte {
	if x != nil {
		return x.CurrentDigest
	}
	return nil
}

type DeltaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetDigest  []byte                 `protobuf:"bytes,1,opt,name=target_digest,json=targetDigest,proto3" json:"target_digest,omitempty"`
	BlockSize     uint32                 `protobuf:"varint,2,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	Signature     []*BlockSignature      `protobuf:"bytes,3,rep,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeltaRequest) Reset() {
	*x = DeltaRequest{}
	mi := &file_hubsync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeltaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeltaRequest) ProtoMessage() {}

func (x *DeltaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hubsync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeltaRequest.ProtoReflect.Descriptor instead.
func (*DeltaRequest) Descriptor() ([]byte, []int) {
	return file_hubsync_proto_rawDescGZIP(), []int{9}
}

func (x *DeltaRequest) GetTargetDigest() []byte {
	if x != nil {
		return x.TargetDigest
	}
	return nil
}

func (x *DeltaRequest) GetBlockSize() uint32 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *DeltaRequest) GetSignature() []*BlockSignature {
	if x != nil {
		return x.Signature
	}
	return nil
}

type BlockSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	WeakHash      uint32                 `protobuf:"varint,2,opt,name=weak_hash,json=weakHash,proto3" json:"weak_hash,omitempty"`
	StrongHash    []byte                 `protobuf:"bytes,3,opt,name=strong_hash,json=strongHash,proto3" json:"strong_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockSignature) Reset() {
	*x = BlockSignature{}
	mi := &file_hubsync_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockSignature) ProtoMessage() {}

func (x *BlockSignature) ProtoReflect() protoreflect.Message {
	mi := &file_hubsync_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockSignature.ProtoReflect.Descriptor instead.
func (*BlockSignature) Descriptor() ([]byte, []int) {
	return file_hubsync_proto_rawDescGZIP(), []int{10}
}

func (x *BlockSignature) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BlockSignature) GetWeakHash() uint32 {
	if x != nil {
		return x.WeakHash
	}
	return 0
}

func (x *BlockSignature) GetStrongHash() []byte {
	if x != nil {
		return x.StrongHash
	}
	return nil
}

type DeltaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetDigest  []byte                 `protobuf:"bytes,1,opt,name=target_digest,json=targetDigest,proto3" json:"target_digest,omitempty"`
	TargetSize    uint64                 `protobuf:"varint,2,opt,name=target_size,json=targetSize,proto3" json:"target_size,omitempty"`
	Ops           []*DeltaOp             `protobuf:"bytes,3,rep,name=ops,proto3" json:"ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeltaResponse) Reset() {
	*x = DeltaResponse{}
	mi := &file_hubsync_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeltaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeltaResponse) ProtoMessage() {}

func (x *DeltaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hubsync_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeltaResponse.ProtoReflect.Descriptor instead.
func (*DeltaResponse) Descriptor() ([]byte, []int) {
	return file_hubsync_proto_rawDescGZIP(), []int{11}
}

func (x *DeltaResponse) GetTargetDigest() []byte {
	if x != nil {
		return x.TargetDigest
	}
	return nil
}

func (x *DeltaResponse) GetTargetSize() uint64 {
	if x != nil {
		return x.TargetSize
	}
	return 0
}

func (x *DeltaResponse) GetOps() []*DeltaOp {
	if x != nil {
		return x.Ops
	}
	return nil
}

type DeltaOp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*DeltaOp_CopyIndex
	//	*DeltaOp_Data
	Op            isDeltaOp_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeltaOp) Reset() {
	*x = DeltaOp{}
	mi := &file_hubsync_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeltaOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeltaOp) ProtoMessage() {}

func (x *DeltaOp) ProtoReflect() protoreflect.Message {
	mi := &file_hubsync_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeltaOp.ProtoReflect.Descriptor instead.
func (*DeltaOp) Descriptor() ([]byte, []int) {
	return file_hubsync_proto_rawDescGZIP(), []int{12}
}

func (x *DeltaOp) GetOp() isDeltaOp_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *DeltaOp) GetCopyIndex() uint32 {
	if x != nil {
		if x, ok := x.Op.(*DeltaOp_CopyIndex); ok {
			return x.CopyIndex
		}
	}
	return 0
}

func (x *DeltaOp) GetData() []byte {
	if x != nil {
		if x, ok := x.Op.(*DeltaOp_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isDeltaOp_Op interface {
	isDeltaOp_Op()
}

type DeltaOp_CopyIndex struct {
	CopyIndex uint32 `protobuf:"varint,1,opt,name=copy_index,json=copyIndex,proto3,oneof"`
}

type DeltaOp_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*DeltaOp_CopyIndex) isDeltaOp_Op() {}

func (*DeltaOp_Data) isDeltaOp_Op() {}

var File_hubsync_proto protoreflect.FileDescriptor

const file_hubsync_proto_rawDesc = "" +
	"\n" +
	"\rhubsync.proto\x12\ahubsync\"\xa0\x01\n" +
	"\tSyncEvent\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12-\n" +
	"\x06change\x18\x03 \x01(\v2\x13.hubsync.FileChangeH\x00R\x06change\x12-\n" +
	"\x06delete\x18\x04 \x01(\v2\x13.hubsync.FileDeleteH\x00R\x06deleteB\a\n" +
	"\x05event\"\x9e\x01\n" +
	"\n" +
	"FileChange\x12&\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x12.hubsync.EntryKindR\x04kind\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\fR\x06digest\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\rR\x04mode\x12\x14\n" +
	"\x05mtime\x18\x05 \x01(\x03R\x05mtime\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\"\f\n" +
	"\n" +
	"FileDelete\"j\n" +
	"\vPushRequest\x12!\n" +
	"\x03ops\x18\x01 \x03(\v2\x0f.hubsync.PushOpR\x03ops\x128\n" +
	"\von_conflict\x18\x02 \x01(\x0e2\x17.hubsync.ConflictPolicyR\n" +
	"onConflict\"\x8c\x01\n" +
	"\x06PushOp\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1f\n" +
	"\x02op\x18\x02 \x01(\x0e2\x0f.hubsync.OpKindR\x02op\x12!\n" +
	"\fbase_version\x18\x03 \x01(\x04R\vbaseVersion\x12\x16\n" +
	"\x06digest\x18\x04 \x01(\fR\x06digest\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\"=\n" +
	"\fPushResponse\x12-\n" +
	"\aresults\x18\x01 \x03(\v2\x13.hubsync.PushResultR\aresults\"\x95\x01\n" +
	"\n" +
	"PushResult\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x123\n" +
	"\baccepted\x18\x02 \x01(\v2\x15.hubsync.PushAcceptedH\x00R\baccepted\x123\n" +
	"\bconflict\x18\x03 \x01(\v2\x15.hubsync.PushConflictH\x00R\bconflictB\t\n" +
	"\aoutcome\"(\n" +
	"\fPushAccepted\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\"v\n" +
	"\fPushConflict\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12'\n" +
	"\x0fcurrent_version\x18\x02 \x01(\x04R\x0ecurrentVersion\x12%\n" +
	"\x0ecurrent_digest\x18\x03 \x01(\fR\rcurrentDigest\"\x89\x01\n" +
	"\fDeltaRequest\x12#\n" +
	"\rtarget_digest\x18\x01 \x01(\fR\ftargetDigest\x12\x1d\n" +
	"\n" +
	"block_size\x18\x02 \x01(\rR\tblockSize\x125\n" +
	"\tsignature\x18\x03 \x03(\v2\x17.hubsync.BlockSignatureR\tsignature\"d\n" +
	"\x0eBlockSignature\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x1b\n" +
	"\tweak_hash\x18\x02 \x01(\rR\bweakHash\x12\x1f\n" +
	"\vstrong_hash\x18\x03 \x01(\fR\n" +
	"strongHash\"y\n" +
	"\rDeltaResponse\x12#\n" +
	"\rtarget_digest\x18\x01 \x01(\fR\ftargetDigest\x12\x1f\n" +
	"\vtarget_size\x18\x02 \x01(\x04R\n" +
	"targetSize\x12\"\n" +
	"\x03ops\x18\x03 \x03(\v2\x10.hubsync.DeltaOpR\x03ops\"F\n" +
	"\aDeltaOp\x12\x1f\n" +
	"\n" +
	"copy_index\x18\x01 \x01(\rH\x00R\tcopyIndex\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\x04\n" +
	"\x02op*1\n" +
	"\tEntryKind\x12\b\n" +
	"\x04FILE\x10\x00\x12\r\n" +
	"\tDIRECTORY\x10\x01\x12\v\n" +
	"\aSYMLINK\x10\x02*5\n" +
	"\x06OpKind\x12\r\n" +
	"\tOP_CREATE\x10\x00\x12\r\n" +
	"\tOP_UPDATE\x10\x01\x12\r\n" +
	"\tOP_DELETE\x10\x02*9\n" +
	"\x0eConflictPolicy\x12\b\n" +
	"\x04FAIL\x10\x00\x12\f\n" +
	"\bHUB_WINS\x10\x01\x12\x0f\n" +
	"\vCLIENT_WINS\x10\x02B\x1bZ\x19github.com/hayeah/hubsyncb\x06proto3"

var (
	file_hubsync_proto_rawDescOnce sync.Once
	file_hubsync_proto_rawDescData []byte
)

func file_hubsync_proto_rawDescGZIP() []byte {
	file_hubsync_proto_rawDescOnce.Do(func() {
		file_hubsync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hubsync_proto_rawDesc), len(file_hubsync_proto_rawDesc)))
	})
	return file_hubsync_proto_rawDescData
}

var file_hubsync_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_hubsync_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_hubsync_proto_goTypes = []any{
	(EntryKind)(0),         // 0: hubsync.EntryKind
	(OpKind)(0),            // 1: hubsync.OpKind
	(ConflictPolicy)(0),    // 2: hubsync.ConflictPolicy
	(*SyncEvent)(nil),      // 3: hubsync.SyncEvent
	(*FileChange)(nil),     // 4: hubsync.FileChange
	(*FileDelete)(nil),     // 5: hubsync.FileDelete
	(*PushRequest)(nil),    // 6: hubsync.PushRequest
	(*PushOp)(nil),         // 7: hubsync.PushOp
	(*PushResponse)(nil),   // 8: hubsync.PushResponse
	(*PushResult)(nil),     // 9: hubsync.PushResult
	(*PushAccepted)(nil),   // 10: hubsync.PushAccepted
	(*PushConflict)(nil),   // 11: hubsync.PushConflict
	(*DeltaRequest)(nil),   // 12: hubsync.DeltaRequest
	(*BlockSignature)(nil), // 13: hubsync.BlockSignature
	(*DeltaResponse)(nil),  // 14: hubsync.DeltaResponse
	(*DeltaOp)(nil),        // 15: hubsync.DeltaOp
}
var file_hubsync_proto_depIdxs = []int32{
	4,  // 0: hubsync.SyncEvent.change:type_name -> hubsync.FileChange
	5,  // 1: hubsync.SyncEvent.delete:type_name -> hubsync.FileDelete
	0,  // 2: hubsync.FileChange.kind:type_name -> hubsync.EntryKind
	7,  // 3: hubsync.PushRequest.ops:type_name -> hubsync.PushOp
	2,  // 4: hubsync.PushRequest.on_conflict:type_name -> hubsync.ConflictPolicy
	1,  // 5: hubsync.PushOp.op:type_name -> hubsync.OpKind
	9,  // 6: hubsync.PushResponse.results:type_name -> hubsync.PushResult
	10, // 7: hubsync.PushResult.accepted:type_name -> hubsync.PushAccepted
	11, // 8: hubsync.PushResult.conflict:type_name -> hubsync.PushConflict
	13, // 9: hubsync.DeltaRequest.signature:type_name -> hubsync.BlockSignature
	15, // 10: hubsync.DeltaResponse.ops:type_name -> hubsync.DeltaOp
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_hubsync_proto_init() }
func file_hubsync_proto_init() {
	if File_hubsync_proto != nil {
		return
	}
	file_hubsync_proto_msgTypes[0].OneofWrappers = []any{
		(*SyncEvent_Change)(nil),
		(*SyncEvent_Delete)(nil),
	}
	file_hubsync_proto_msgTypes[6].OneofWrappers = []any{
		(*PushResult_Accepted)(nil),
		(*PushResult_Conflict)(nil),
	}
	file_hubsync_proto_msgTypes[12].OneofWrappers = []any{
		(*DeltaOp_CopyIndex)(nil),
		(*DeltaOp_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hubsync_proto_rawDesc), len(file_hubsync_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hubsync_proto_goTypes,
		DependencyIndexes: file_hubsync_proto_depIdxs,
		EnumInfos:         file_hubsync_proto_enumTypes,
		MessageInfos:      file_hubsync_proto_msgTypes,
	}.Build()
	File_hubsync_proto = out.File
	file_hubsync_proto_goTypes = nil
	file_hubsync_proto_depIdxs = nil
}
