// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: hubsync.proto

package hubsync

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntryKind int32

const (
	EntryKind_FILE      EntryKind = 0
	EntryKind_DIRECTORY EntryKind = 1
	EntryKind_SYMLINK   EntryKind = 2
)

// Enum value maps for EntryKind.
var (
	EntryKind_name = map[int32]string{
		0: "FILE",
		1: "DIRECTORY",
		2: "SYMLINK",
	}
	EntryKind_value = map[string]int32{
		"FILE":      0,
		"DIRECTORY": 1,
		"SYMLINK":   2,
	}
)

func (x EntryKind) Enum() *EntryKind {
	p := new(EntryKind)
	*p = x
	return p
}

func (x EntryKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryKind) Descriptor() protoreflect.EnumDescriptor {
	return file_hubsync_proto_enumTypes[0].Descriptor()
}

func (EntryKind) Type() protoreflect.EnumType {
	return &file_hubsync_proto_enumTypes[0]
}

func (x EntryKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryKind.Descriptor instead.
func (EntryKind) EnumDescriptor() ([]byte, []int) {
	return file_hubsync_proto_rawDescGZIP(), []int{0}
}

type SyncEvent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Path    string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*SyncEvent_Change
	//	*SyncEvent_Delete
	Event         isSyncEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncEvent) Reset() {
	*x = SyncEvent{}
	mi := &file_hubsync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncEvent) ProtoMessage() {}

func (x *SyncEvent) ProtoReflect() protoreflect.Message {
	mi := &file_hubsync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncEvent.ProtoReflect.Descriptor instead.
func (*SyncEvent) Descriptor() ([]byte, []int) {
	return file_hubsync_proto_rawDescGZIP(), []int{0}
}

func (x *SyncEvent) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SyncEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SyncEvent) GetEvent() isSyncEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SyncEvent) GetChange() *FileChange {
	if x != nil {
		if x, ok := x.Event.(*SyncEvent_Change); ok {
			return x.Change
		}
	}
	return nil
}

func (x *SyncEvent) GetDelete() *FileDelete {
	if x != nil {
		if x, ok := x.Event.(*SyncEvent_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

type isSyncEvent_Event interface {
	isSyncEvent_Event()
}

type SyncEvent_Change struct {
	Change *FileChange `protobuf:"bytes,3,opt,name=change,proto3,oneof"`
}

type SyncEvent_Delete struct {
	Delete *FileDelete `protobuf:"bytes,4,opt,name=delete,proto3,oneof"`
}

func (*SyncEvent_Change) isSyncEvent_Event() {}

func (*SyncEvent_Delete) isSyncEvent_Event() {}

type FileChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          EntryKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=hubsync.EntryKind" json:"kind,omitempty"`
	Digest        []byte                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Mode          uint32                 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	Mtime         int64                  `protobuf:"varint,5,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"` // inline blob for files <= 64KB; empty for large files
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChange) Reset() {
	*x = FileChange{}
	mi := &file_hubsync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChange) ProtoMessage() {}

func (x *FileChange) ProtoReflect() protoreflect.Message {
	mi := &file_hubsync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChange.ProtoReflect.Descriptor instead.
func (*FileChange) Descriptor() ([]byte, []int) {
	return file_hubsync_proto_rawDescGZIP(), []int{1}
}

func (x *FileChange) GetKind() EntryKind {
	if x != nil {
		return x.Kind
	}
	return EntryKind_FILE
}

func (x *FileChange) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *FileChange) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileChange) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileChange) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *FileChange) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type FileDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDelete) Reset() {
	*x = FileDelete{}
	mi := &file_hubsync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDelete) ProtoMessage() {}

func (x *FileDelete) ProtoReflect() protoreflect.Message {
	mi := &file_hubsync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDelete.ProtoReflect.Descriptor instead.
func (*FileDelete) Descriptor() ([]byte, []int) {
	return file_hubsync_proto_rawDescGZIP(), []int{2}
}

var File_hubsync_proto protoreflect.FileDescriptor

const file_hubsync_proto_rawDesc = "" +
	"\n" +
	"\rhubsync.proto\x12\ahubsync\"\xa0\x01\n" +
	"\tSyncEvent\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12-\n" +
	"\x06change\x18\x03 \x01(\v2\x13.hubsync.FileChangeH\x00R\x06change\x12-\n" +
	"\x06delete\x18\x04 \x01(\v2\x13.hubsync.FileDeleteH\x00R\x06deleteB\a\n" +
	"\x05event\"\x9e\x01\n" +
	"\n" +
	"FileChange\x12&\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x12.hubsync.EntryKindR\x04kind\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\fR\x06digest\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\rR\x04mode\x12\x14\n" +
	"\x05mtime\x18\x05 \x01(\x03R\x05mtime\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\"\f\n" +
	"\n" +
	"FileDelete*1\n" +
	"\tEntryKind\x12\b\n" +
	"\x04FILE\x10\x00\x12\r\n" +
	"\tDIRECTORY\x10\x01\x12\v\n" +
	"\aSYMLINK\x10\x02B\x1bZ\x19github.com/hayeah/hubsyncb\x06proto3"

var (
	file_hubsync_proto_rawDescOnce sync.Once
	file_hubsync_proto_rawDescData []byte
)

func file_hubsync_proto_rawDescGZIP() []byte {
	file_hubsync_proto_rawDescOnce.Do(func() {
		file_hubsync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hubsync_proto_rawDesc), len(file_hubsync_proto_rawDesc)))
	})
	return file_hubsync_proto_rawDescData
}

var file_hubsync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hubsync_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_hubsync_proto_goTypes = []any{
	(EntryKind)(0),     // 0: hubsync.EntryKind
	(*SyncEvent)(nil),  // 1: hubsync.SyncEvent
	(*FileChange)(nil), // 2: hubsync.FileChange
	(*FileDelete)(nil), // 3: hubsync.FileDelete
}
var file_hubsync_proto_depIdxs = []int32{
	2, // 0: hubsync.SyncEvent.change:type_name -> hubsync.FileChange
	3, // 1: hubsync.SyncEvent.delete:type_name -> hubsync.FileDelete
	0, // 2: hubsync.FileChange.kind:type_name -> hubsync.EntryKind
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_hubsync_proto_init() }
func file_hubsync_proto_init() {
	if File_hubsync_proto != nil {
		return
	}
	file_hubsync_proto_msgTypes[0].OneofWrappers = []any{
		(*SyncEvent_Change)(nil),
		(*SyncEvent_Delete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hubsync_proto_rawDesc), len(file_hubsync_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hubsync_proto_goTypes,
		DependencyIndexes: file_hubsync_proto_depIdxs,
		EnumInfos:         file_hubsync_proto_enumTypes,
		MessageInfos:      file_hubsync_proto_msgTypes,
	}.Build()
	File_hubsync_proto = out.File
	file_hubsync_proto_goTypes = nil
	file_hubsync_proto_depIdxs = nil
}
