// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package hubsync

import (
	_ "modernc.org/sqlite"
)

// Injectors from wire.go:

// InitializeTestHubApp creates a HubApp for testing.
func InitializeTestHubApp(cfg *HubConfig) (*HubApp, func(), error) {
	hubStore, cleanup, err := ProvideHubStore(cfg)
	if err != nil {
		return nil, nil, err
	}
	scanner, err := ProvideScanner(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	watcher, cleanup2, err := ProvideWatcher(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	broadcaster := NewBroadcaster()
	hub := NewHub(hubStore, scanner, watcher, broadcaster)
	server := ProvideServer(hub, cfg)
	hubApp := &HubApp{
		Server: server,
		Hub:    hub,
	}
	return hubApp, func() {
		cleanup2()
		cleanup()
	}, nil
}

// InitializeTestClientApp creates a ClientApp for testing.
func InitializeTestClientApp(cfg *ClientConfig) (*ClientApp, func(), error) {
	clientStore, cleanup, err := ProvideClientStore(cfg)
	if err != nil {
		return nil, nil, err
	}
	client := ProvideClient(clientStore, cfg)
	clientApp := &ClientApp{
		Client: client,
	}
	return clientApp, func() {
		cleanup()
	}, nil
}
